export default {
    SET_MESSAGES: 'SET_MESSAGES',
    SET_PENDINGMESSAGES: 'SET_PENDINGMESSAGES',
    ADD_PENDINGMESSAGES:'ADD_PENDINGMESSAGES',
    REMOVE_PENDINGMESSAGES:'REMOVE_PENDINGMESSAGES',
    ADD_MESSAGE:'ADD_MESSAGE',
    SET_CONNECTION:'SET_CONNECTION',
    SET_CONVERSATIONS:'SET_CONVERSATIONS',
    SET_CONVERSATIONSLOAD:'SET_CONVERSATIONSLOAD'
}